[package]
name = "linear-path"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.23.0"
obj = {path = "./src/crates/obj", version="0.0.0"}